"""VectorRAG: semantic similarity search over node embeddings (Algorithm 2, Section 3.3.2).

Embeds the global_semantic / local_semantic text descriptions (generated by
semantic_enrichment.py) using a local HuggingFace sentence-transformers model,
stores the vectors on the Neo4j nodes, creates vector indexes, and provides
cosine-similarity search to find the nodes most relevant to a query.

The paper uses Voyage-3.5-lite (1024-dim). We use all-MiniLM-L6-v2 (384-dim)
locally — no API key needed, runs on CPU. Swap via CHATPID_EMBEDDING_MODEL.
"""

from __future__ import annotations

from neo4j import Driver

from chatpid.config import get_settings

# Lazy-loaded embedder (loading the model takes ~3s)
_embedder = None


def _get_embedder():
    global _embedder
    if _embedder is None:
        from langchain_huggingface import HuggingFaceEmbeddings
        settings = get_settings()
        _embedder = HuggingFaceEmbeddings(model_name=settings.embedding_model)
    return _embedder


def embed_text(text: str) -> list[float]:
    """Embed a text string using the configured embedding model."""
    return _get_embedder().embed_query(text)


def embed_and_store(driver: Driver, level: str = "conceptual") -> int:
    """Embed all nodes' semantic descriptions and store vectors on the nodes.

    Requires that enrich_all_nodes() has been run first (so global_semantic
    and local_semantic properties exist on the nodes).

    Returns the number of nodes embedded.
    """
    embedder = _get_embedder()

    with driver.session() as session:
        # Get all nodes with semantic descriptions
        result = session.run(
            """
            MATCH (n {level: $level})
            WHERE n.global_semantic IS NOT NULL AND n.local_semantic IS NOT NULL
            RETURN elementId(n) AS eid, n.global_semantic AS global_sem, n.local_semantic AS local_sem
            """,
            level=level,
        )
        nodes = [dict(r) for r in result]

        print(f"Embedding {len(nodes)} nodes...")
        count = 0
        for node in nodes:
            global_vec = embedder.embed_query(node["global_sem"])
            local_vec = embedder.embed_query(node["local_sem"])

            session.run(
                """
                MATCH (n) WHERE elementId(n) = $eid
                SET n.global_semantic_embedding = $global_vec,
                    n.local_semantic_embedding = $local_vec
                """,
                eid=node["eid"],
                global_vec=global_vec,
                local_vec=local_vec,
            )
            count += 1
            if count % 10 == 0:
                print(f"  {count}/{len(nodes)} embedded")

        return count


def ensure_vector_indexes(driver: Driver, dimensions: int = 384) -> None:
    """Create Neo4j vector indexes for global/local semantic embeddings."""
    with driver.session() as session:
        for index_name, prop in (
            ("global_semantic_index", "global_semantic_embedding"),
            ("local_semantic_index", "local_semantic_embedding"),
        ):
            session.run(
                f"""
                CREATE VECTOR INDEX {index_name} IF NOT EXISTS
                FOR (n:Node) ON (n.{prop})
                OPTIONS {{indexConfig: {{
                    `vector.dimensions`: $dimensions,
                    `vector.similarity_function`: 'cosine'
                }}}}
                """,
                dimensions=dimensions,
            )
    print(f"Vector indexes ensured (dimensions={dimensions})")


def vector_rag(
    driver: Driver,
    query: str,
    index: str = "global_semantic_index",
    top_k: int = 5,
    level: str = "conceptual",
) -> list[dict]:
    """Return the top-k nodes whose semantic embedding is closest to `query`.

    Args:
        query: natural language query
        index: "global_semantic_index" or "local_semantic_index"
        top_k: number of results
        level: graph level to filter by
    """
    query_vector = embed_text(query)
    embedding_prop = (
        "global_semantic_embedding"
        if index == "global_semantic_index"
        else "local_semantic_embedding"
    )

    cypher = """
    CALL db.index.vector.queryNodes($index, $top_k, $query_vector)
    YIELD node, score
    WHERE node.level = $level
    RETURN node.tag AS tag, labels(node) AS labels,
           node.global_semantic AS global_semantic,
           node.local_semantic AS local_semantic,
           score
    ORDER BY score DESC
    """
    with driver.session() as session:
        results = session.run(
            cypher, index=index, top_k=top_k, query_vector=query_vector, level=level
        )
        return [
            {
                "tag": r["tag"],
                "label": [l for l in (r["labels"] or []) if l != "Node"][0] if r["labels"] else "",
                "global_semantic": r["global_semantic"],
                "local_semantic": r["local_semantic"],
                "score": r["score"],
            }
            for r in results
        ]


def vector_rag_text(
    driver: Driver,
    query: str,
    index: str = "global_semantic_index",
    top_k: int = 5,
    level: str = "conceptual",
) -> str:
    """Convenience wrapper: return VectorRAG results as formatted text."""
    results = vector_rag(driver, query, index, top_k, level)
    if not results:
        return "No relevant nodes found."

    lines = [f"VectorRAG results (top {len(results)}, index={index}):"]
    for i, r in enumerate(results, 1):
        lines.append(f"\n[{i}] {r['tag']} ({r['label']}) — score: {r['score']:.4f}")
        sem = r["global_semantic"] if index == "global_semantic_index" else r["local_semantic"]
        if sem:
            lines.append(f"    {sem[:200]}")
    return "\n".join(lines)
