"""Generate a genuinely large, structurally-realistic synthetic P&ID.

Uses pyDEXPI's built-in synthetic generation framework with the official DEXPI
sample patterns (pump, heat exchanger, column, reactor, compressor, mixer,
storage, feed, product) to build a realistic process flowsheet by composing
equipment patterns into a coherent diagram.

This is NOT a tiled copy of the 36-node reference diagram — it uses genuinely
different equipment types (columns, reactors, compressors) with realistic
process topology generated by pyDEXPI's RandomGeneratorFunction.

The generated P&ID is ingested directly into Neo4j (bypassing XML export due to
pyDEXPI version compatibility issues with the Proteus exporter).

Usage:
    uv run python scripts/21_generate_synthetic_pid.py
    uv run python scripts/21_generate_synthetic_pid.py --target-nodes 200 --ingest
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

PATTERNS_DIR = Path(__file__).resolve().parent.parent / "data" / "dexpi_sample_patterns"
RAW_DIR = Path(__file__).resolve().parent.parent / "data" / "raw"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target-nodes",
        type=int,
        default=150,
        help="Target number of nodes (default: 150)",
    )
    parser.add_argument(
        "--seed", type=int, default=42, help="Random seed for reproducibility"
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=None,
        help="Max generation steps (default: target_nodes // 8)",
    )
    parser.add_argument(
        "--ingest",
        action="store_true",
        help="Ingest the generated P&ID into Neo4j after generation",
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Clear existing Neo4j data before ingesting (use with --ingest)",
    )
    parser.add_argument(
        "--persist",
        action="store_true",
        help="Persist generated graphs to disk as GraphML in data/synthetic/",
    )
    parser.add_argument(
        "--persist-dir",
        default="data/synthetic",
        help="Directory to persist graphs to (default: data/synthetic)",
    )
    args = parser.parse_args()

    import random

    random.seed(args.seed)
    import numpy as np

    np.random.seed(args.seed)

    # Load all pattern distributions
    from pydexpi.syndata import PatternDistribution, SyntheticPIDGenerator
    from pydexpi.syndata.connector_renaming import ConnectorRenamingConvention
    from pydexpi.syndata.generator_function import (
        CappingFunction,
        RandomGeneratorFunction,
    )

    print("Loading DEXPI sample pattern distributions...")
    pattern_distr_names = [
        name for name in os.listdir(PATTERNS_DIR) if (PATTERNS_DIR / name).is_dir()
    ]
    distributions = [
        PatternDistribution.load(PATTERNS_DIR, name) for name in pattern_distr_names
    ]
    distribution_dict = {d.name: d for d in distributions}
    for d in distributions:
        print(
            f"  {d.name}: {len(d.patterns)} patterns, connectors={d.connector_labels}"
        )

    # Create generator function with random pattern selection
    generator_function = RandomGeneratorFunction(
        distribution_dict,
        p_connect_internal=0.1,  # 10% chance of recycle connections
        use_distribution_probabilities=True,
    )

    # Cap open connectors with product patterns
    capping_function = CappingFunction({"product": distribution_dict["product"]})
    renaming = ConnectorRenamingConvention()

    max_steps = args.max_steps or max(args.target_nodes // 8, 20)
    print(f"\nMax generation steps: {max_steps}")

    generator = SyntheticPIDGenerator(
        generator_function=generator_function,
        capping_function=capping_function,
        renaming_convention=renaming,
        max_steps=max_steps,
    )

    print("Generating synthetic P&ID...")
    try:
        result_pattern = generator.generate_pattern("synthetic_pid")
        print("Generation complete!")
    except Exception as e:
        print(f"Generation error: {e}")
        import traceback

        traceback.print_exc()
        return

    # Extract the DexpiModel
    model = result_pattern.dexpi_model
    print(f"DexpiModel type: {type(model).__name__}")

    # Build graph abstractions directly from the model
    from chatpid.ingest import (
        build_graph_abstractions,
        get_driver,
        load_graph,
    )

    print("\nBuilding graph abstractions...")
    graphs = build_graph_abstractions(model)

    for level in ["complete", "process", "conceptual"]:
        g = getattr(graphs, level)
        print(f"  {level}: {g.number_of_nodes()} nodes, {g.number_of_edges()} edges")

    # Count equipment types in the conceptual graph
    equipment_types = {}
    for n, data in graphs.conceptual.nodes(data=True):
        label = data.get("label", "Unknown")
        equipment_types[label] = equipment_types.get(label, 0) + 1
    print(f"\nEquipment types in conceptual graph ({len(equipment_types)} unique):")
    for etype, count in sorted(equipment_types.items(), key=lambda x: -x[1]):
        print(f"  {etype}: {count}")

    # Compare with reference P&ID
    print("\n--- Comparison with reference P&ID (C01V04-VER.EX01) ---")
    print("  Reference conceptual: 36 nodes, 36 edges")
    print(
        f"  Synthetic conceptual: {graphs.conceptual.number_of_nodes()} nodes, "
        f"{graphs.conceptual.number_of_edges()} edges"
    )

    # Persist graphs to disk as GraphML so they survive Neo4j restarts
    if args.persist:
        import json

        import networkx as nx

        persist_dir = Path(args.persist_dir)
        persist_dir.mkdir(parents=True, exist_ok=True)

        # Save metadata
        meta = {
            "seed": args.seed,
            "max_steps": max_steps,
            "target_nodes": args.target_nodes,
            "equipment_types": equipment_types,
            "node_counts": {
                "complete": graphs.complete.number_of_nodes(),
                "process": graphs.process.number_of_nodes(),
                "conceptual": graphs.conceptual.number_of_nodes(),
            },
            "edge_counts": {
                "complete": graphs.complete.number_of_edges(),
                "process": graphs.process.number_of_edges(),
                "conceptual": graphs.conceptual.number_of_edges(),
            },
        }
        meta_path = persist_dir / "metadata.json"
        with open(meta_path, "w") as f:
            json.dump(meta, f, indent=2)
        print(f"\nSaved metadata: {meta_path}")

        # Save each level as GraphML
        for level in ["complete", "process", "conceptual"]:
            g = getattr(graphs, level)
            # GraphML doesn't support all Python types; convert non-primitive to str
            for n, data in g.nodes(data=True):
                for k, v in list(data.items()):
                    if not isinstance(v, (str, int, float, bool, type(None))):
                        data[k] = str(v)
            graphml_path = persist_dir / f"{level}.graphml"
            nx.write_graphml(g, graphml_path)
            print(f"Saved {level}: {graphml_path} ({g.number_of_nodes()} nodes)")
        print(f"\nAll graphs persisted to {persist_dir}/")
        print("To re-ingest from disk: uv run python scripts/23_ingest_synthetic.py")

    if args.ingest:
        print("\n--- Ingesting into Neo4j ---")
        driver = get_driver()
        try:
            if args.clear:
                print("Clearing existing synthetic data...")
                with driver.session() as session:
                    session.run("MATCH (n {document_id: 'synthetic'}) DETACH DELETE n")

            for level in ["complete", "process", "conceptual"]:
                g = getattr(graphs, level)
                print(f"  Loading {level} ({g.number_of_nodes()} nodes)...")
                load_graph(driver, g, level, document_id="synthetic")
            print("Ingestion complete!")
        finally:
            driver.close()
    else:
        print("\n(use --ingest to load into Neo4j)")


if __name__ == "__main__":
    main()
